version: "3.3"

services:
  app-nginx:
    image: nginx:alpine
    container_name: "pid-nginx"
    ports:
      - "8888:80"
    volumes:
      - ./:/current
      - ./_docker/routing/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./_docker/routing/fastcgi_params:/etc/nginx/fastcgi_params:ro
      - ./_docker/routing/conf.d/:/etc/nginx/conf.d:ro
    networks:
      - app-network
volumes:
  app-db-data:
  app-code:

networks:
  app-network:

